# Estágio 1: Build da aplicação
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
# Baixa as dependências offline para otimizar cache
RUN mvn dependency:go-offline
COPY src ./src
# Compila o .jar pulando os testes para ser mais rápido
RUN mvn clean package -DskipTests

# Estágio 2: Imagem final para rodar a aplicação
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]