/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#586064",
        "on-primary": "#dffff0",
        "on-secondary-fixed": "#36404d",
        "on-surface": "#2b3437",
        "surface-container-high": "#e2e9ec",
        "tertiary-dim": "#4a5739",
        "on-tertiary-container": "#4f5d3e",
        "on-tertiary-fixed": "#3d4a2e",
        "on-background": "#2b3437",
        "error-container": "#fe8983",
        "on-error-container": "#752121",
        "secondary-fixed-dim": "#cbd5e6",
        "surface-variant": "#dbe4e7",
        "primary": "#2b6954",
        "on-error": "#fff7f6",
        "surface-dim": "#d1dce0",
        "tertiary-container": "#e4f4cc",
        "error": "#9f403d",
        "on-secondary-container": "#485260",
        "outline": "#737c7f",
        "on-tertiary-fixed-variant": "#596748",
        "on-primary-fixed-variant": "#286652",
        "tertiary-fixed-dim": "#d6e5be",
        "tertiary": "#566445",
        "surface-container": "#eaeff1",
        "on-tertiary": "#efffd6",
        "tertiary-fixed": "#e4f4cc",
        "primary-fixed-dim": "#a2e2c8",
        "error-dim": "#4e0309",
        "surface-container-highest": "#dbe4e7",
        "surface-container-low": "#f1f4f6",
        "on-primary-fixed": "#004936",
        "on-secondary-fixed-variant": "#525c6a",
        "surface-tint": "#2b6954",
        "primary-fixed": "#b0f0d6",
        "inverse-primary": "#b8f9de",
        "secondary-container": "#d9e3f4",
        "on-primary-container": "#1c5c48",
        "secondary-fixed": "#d9e3f4",
        "on-secondary": "#f7f9ff",
        "primary-dim": "#1d5d49",
        "secondary": "#56606e",
        "surface-bright": "#f8f9fa",
        "background": "#f8f9fa",
        "outline-variant": "#abb3b7",
        "primary-container": "#b0f0d6",
        "secondary-dim": "#4a5462",
        "surface": "#f8f9fa",
        "inverse-surface": "#0c0f10",
        "inverse-on-surface": "#9b9d9e",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}